"""init: services, service_checks, service_statistics

Revision ID: 141487a0fcb5
Revises: 
Create Date: 2026-06-20 18:55:23.468125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '141487a0fcb5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('endpoint_url', sa.String(length=2048), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('check_interval_seconds', sa.Integer(), server_default='60', nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('service_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_checks_checked_at'), 'service_checks', ['checked_at'], unique=False)
    op.create_index(op.f('ix_service_checks_service_id'), 'service_checks', ['service_id'], unique=False)
    op.create_table('service_statistics',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('total_checks', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed_checks', sa.Integer(), server_default='0', nullable=False),
    sa.Column('avg_response_time_ms', sa.Float(), nullable=True),
    sa.Column('uptime_percentage', sa.Float(), server_default='100', nullable=False),
    sa.Column('current_status', sa.Enum('online', 'degraded', 'offline', 'unknown', name='service_status'), server_default='unknown', nullable=False),
    sa.Column('last_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_response_time_ms', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_statistics')
    op.drop_index(op.f('ix_service_checks_service_id'), table_name='service_checks')
    op.drop_index(op.f('ix_service_checks_checked_at'), table_name='service_checks')
    op.drop_table('service_checks')
    op.drop_table('services')
    # ### end Alembic commands ###
